version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.5.0
    environment:
      - "discovery.type=single-node"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
    ports:
      - 9200:9200
      - 9300:9300
  dejavu:
    container_name: dejavu
    image: appbaseio/dejavu:3.3.0
    ports:
      - 8090:1358
