version: "3"
services:
  master:
    container_name: redis-master
    image: redis:5.0.5
    volumes:
      - ~/volumes/redis/conf/master.conf:/usr/local/etc/redis/redis.conf
      - ~/volumes/redis/data/master:/data
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
  replica-node1:
    container_name: redis-replica-node1
    image: redis:5.0.5
    volumes:
      - ~/volumes/redis/conf/replica.conf:/usr/local/etc/redis/redis.conf
      - ~/volumes/redis/data/replica-node1:/data
    ports:
      - 6380:6380
    command: redis-server /usr/local/etc/redis/redis.conf --port 6380